### ISSUE TITLE
Comment obtenir un email/password?

### ISSUE THREAD

**Issue by cedric-villeneuve** [planetefrench/evduty-free#1]
Bonjour !

Désolé pour le ticket qui n'en est pas un, mais je ne trouve pas comment vous contacter.

Est-ce que vous avez une documentation pour l'api de evduty? Je ne trouve rien en ligne.

Je ne trouve pas comment obtenir un email/password qui me permettrait d'avoir accès à l'API / d'obtenir un token

Merci beaucoup !!

**Comment by planetefrench** [comment]
Salut Cédric.

Non, il n'y a pas d'api public, j'ai du faire un peu d'analyse des
communications de l'app.

J'utilise les mêmes creds que dans l'app.

Je dois avouer que je n'y ai pas touché ça fait longtemps, j'ai fait le
minimum pour faire une intégration dans homeassistant. Ça semble encore
fonctionner.

Si tu as besoin d'aide je peux essayer. Dit moi ce que tu essaie de faire
et où tu es rendu et je peux voir.

**Comment by cedvil** [comment]
Finalement j'ai réussi à me connecter à l'API avec postman en utilisant ton code comme exemple, par contre s'il n'y a pas de documentation pour l'API ça va être pas mal difficile de faire ce que je veux. J'avais espéré pouvoir sortir les statistiques de mes recharges au format CSV ou quelque chose comme ça pour me faire des beaux rapports sur les coûts de mes recharges. On peut downloader un CSV dans l'application, mais j'espérais pouvoir automatiser le tout en récupérant les données dans un API. Si jamais tu as une idée de si c'est possible ça serait cool, sinon j'ai contacté evduty, on verra bien, si ça t'intéresse je peux te revenir avec leur réponse. Merci pour la réponse en tout cas !

**Comment by planetefrench** [comment]
Ce serait pas trop dur de rajouter ça. J'ai pas fait le python, mais voici
ta réponse:

hxxps://api.evduty.net/v2/account/stations/
<<station_id>>/terminals/<<terminal_id>>/activities?offset=0&limit=20

Si tu es pas pire en python, tu peux figurer comment obtenir le token
nécessaire et le station_id et terminal_id de ta borne - tout ça est dans
le projet.

**Comment by planetefrench** [comment]
Finalement, il y a une solution pour obtenir le CSV directement. Je regarde
ça ce soir.

**Comment by cedvil** [comment]
Merci beaucoup c'est gentil ! Par curiosité, tu fais comment pour trouver les urls ? Tu as une doc de l'API ?

**Comment by planetefrench** [comment]
Voici: hxxps://api.evduty.net/v1/account/reports/monthly/export/sessions/csv?month=2&year=2024

La façon d'obtenir l'info sur l'API. J'utilise Android Studio avec un
emulateur d'Android, j'installe l'application officielle de EvDuty et
j'utilise HTTPToolkit sur mon PC pour comprendre les requêtes.
