### ISSUE TITLE
assistance et évolution du code

### ISSUE THREAD

**Issue by dubun290** [planetefrench/evduty-free#2]
j'ai fait le test sur ma borne evduty - fonctionne très bien - à quand l'évolution du code pour pouvoir démarrer/prolonger ou arrêter le chargement! J'aimerais bien aussi pouvoir intégrer dans MQTT - si je peux aider avec des tests je suis disponible.

**Comment by planetefrench** [comment]
J'y pense encore, mais j'ai pas eu trop de temps.

Pour arrêter la session, simplement changer le maximum de courant à 0.

`w.set_max_charging_current(stations[0], terminals[0], 0)`

L'inverse pour recommencer:

`w.set_max_charging_current(stations[0], terminals[0], 30)`

**Comment by planetefrench** [comment]
Pour MQTT, je suis pas certain. Je l'utilise dans homeassistant avec [https://github.com/planetefrench/ha-evduty](https://github.com/planetefrench/ha-evduty)

Mais attention, le plugin Homeassistant est terrible et difficile a configurer.

**Comment by planetefrench** [comment]
Hey everyone. I don't have time to fix everything. Seems like there's now a better API - integration:

https://github.com/happydev-ca/evduty-api
https://github.com/happydev-ca/evduty-home-assistant

I just tried them. They seem to work well
