### ISSUE TITLE
Exposer les features de la librairie via MQTT Discovery

### ISSUE THREAD

**Issue by end2endzone** [planetefrench/evduty-free#3]
J'ai lu à propos des issues de `ha-evduty` sur des issues ici ou sur le repo de _ha-evduty_...

Si coder une intégration directement dans HA avec ha-evduty est compliqué, ça serait peut-être plus simple d'exposer les setter/getter de cette librairie via l'intégration [MQTT Discovery](https://www.home-assistant.io/integrations/mqtt/) de Home Assistant. Ça permettrait d'exploser les mêmes devices et entitées que ceux exposé via ha-evduty.

L'idée c'est d'exposer par exemple `w.get_max_charging_current() != 0` en tant que [MQTT binary sensor](https://www.home-assistant.io/integrations/binary_sensor.mqtt/) (un flag on/off read only). Pour un binary sensor, HA afficherait un icône en noir et blanc quand on ne charge pas et un icône en couleur quand on charge.

Pour ce qui est du protocol MQTT, il y a un add-on pour hoster le serveur (mosquitto) directement dans HA. MQTT fonctionne sur le principe de publish/subscribe. Donc on poll avec la librairie les différents states de la borne et on les publish dans MQTT en tant qu'entities. HA les ramasse et les affiche dans le GUI et process ensuite sa liste d'automatisation pour ces entitées. Quand on fait une action avec le gui (par exemple quand on clic sur une switch "charge"), HA publie dans MQTT la transition off -> on. Ensuite ça prend un process qui "listen" pour les transitions MQTT et qui les forward à la lib pour caller quelque chose comme `w.set_max_charging_current(stations[0], terminals[0], 30)`.

Ce qui est pratique c'est que le gui de HA va se construire tout seul. Ça permet d'intégrer n'importe feature de n'importe quel device sans avoir une "intégration officielle".

J'ai travaillé sur un projet perso pour exposer ma sonnette de porte via MQTT avec un ESP32 pour pouvoir faire des automatisations dans HA. Une fois que tous les entitées sont déclarées, ça donne quelque chose comme ça dans le gui:
![image](https://github.com/user-attachments/assets/bfaf1fe0-70ff-4ec1-be02-6bf376e6deb3)

La liste des intégrations pour voir tous les types d'entitées que l'on peut exposer via MQTT Discovery est disponible à https://www.home-assistant.io/integrations/#search/mqtt

Je veux être clair, cette approche s'est seulement valide si c'est effectivement compliqué d'ajouter une intégration dans HA. Naturellement, une intégration dans HACS ça serait l'objectif à atteindre. Une fois qu'on aurait ça, on aurait plus besoin de faire un bridge via MQTT. Sent-toi bien alaise de fermer cette issue si jamais tu veux poursuivre avec ha-evduty.

**Comment by planetefrench** [comment]
Hey everyone. I don't have time to fix everything. Seems like there's now a better API - integration: 

https://github.com/happydev-ca/evduty-api
https://github.com/happydev-ca/evduty-home-assistant

I just tried them. They seem to work well

**Comment by planetefrench** [comment]
Hey everyone. I don't have time to fix everything. Seems like there's now a better API - integration:

https://github.com/happydev-ca/evduty-api
https://github.com/happydev-ca/evduty-home-assistant

I just tried them. They seem to work well
